export const INSIGHT_SUMMARY_SUCCESS = "INSIGHT_SUMMARY_SUCCESS";
export const INSIGHT_SUMMARY_FAILED = "INSIGHT_SUMMARY_FAILED";
export const LOADING_INSIGHT_SUMMARY = "LOADING_INSIGHT_SUMMARY";
export const RESET_INSIGHT_SUMMARY = "RESET_INSIGHT_SUMMARY";


export const CATEGORY_DISTRIBUTION_SUCCESS = "CATEGORY_DISTRIBUTION_SUCCESS";
export const CATEGORY_DISTRIBUTION_FAILED = "CATEGORY_DISTRIBUTION_FAILED";
export const LOADING_CATEGORY_DISTRIBUTION = "LOADING_CATEGORY_DISTRIBUTION";
export const RESET_CATEGORY_DISTRIBUTION = "RESET_CATEGORY_DISTRIBUTION";


export const RESPONSE_TIMES_SUCCESS = "RESPONSE_TIMES_SUCCESS";
export const RESPONSE_TIMES_FAILED = "RESPONSE_TIMES_FAILED";
export const LOADING_RESPONSE_TIMES = "LOADING_RESPONSE_TIMES";
export const RESET_RESPONSE_TIMES = "RESET_RESPONSE_TIMES";


export const USER_SATISFACTION_SUCCESS = "USER_SATISFACTION_SUCCESS";
export const USER_SATISFACTION_FAILED = "USER_SATISFACTION_FAILED";
export const LOADING_USER_SATISFACTION = "LOADING_USER_SATISFACTION";
export const RESET_USER_SATISFACTION = "RESET_USER_SATISFACTION";


export const USAGE_STATISTICS_SUCCESS = "USAGE_STATISTICS_SUCCESS";
export const USAGE_STATISTICS_FAILED = "USAGE_STATISTICS_FAILED";
export const LOADING_USAGE_STATISTICS = "LOADING_USAGE_STATISTICS";
export const RESET_USAGE_STATISTICS = "RESET_USAGE_STATISTICS";